apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cloudflare-tunnel-ingress-controller
      spec:
        replicas: 2
        template:
          spec:
            containers:
            - name: controller
              image: ghcr.io/strrl/cloudflare-tunnel-ingress-controller:v0.0.16  # Use specific version
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
                limits:
                  cpu: 400m
                  memory: 512Mi
              securityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 65534
                allowPrivilegeEscalation: false
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 20
              readinessProbe:
                httpGet:
                  path: /readyz
                  port: 8080
                initialDelaySeconds: 5
                periodSeconds: 10
    target:
      kind: Deployment
      name: cloudflare-tunnel-ingress-controller