apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/pl4nty/cloudflare-kubernetes-gateway/config/default?ref=v0.7.1
  # - namespace.yaml
  # - gateway-class.yaml
  # - gateway.yaml
  # - sealedsecret.yaml