apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-gateway
  namespace: cloudflare-gateway

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudflare-gateway
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]  
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: 
      - "gateways"
      - "gatewayclasses"
      - "httproutes"
      - "tlsroutes"
      - "tcproutes"
      - "udproutes"
      - "referencegrants"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudflare-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudflare-gateway
subjects:
  - kind: ServiceAccount
    name: cloudflare-gateway
    namespace: cloudflare-gateway