---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: cloudflare-gateway
spec:
  encryptedData:
    ACCOUNT_ID: AgCREKhdaaifjyOQgZE1AAqHgJn0cPUas/G0wfiXRms4siNDXD1MAPe9fw5QQu/8SHwE1/+TCsTsXkguk7VAPXdjFtpDFC0ELyn8h+omIFwYvNvcr+AgCuVQ5sIquVqmw2pZ5i2F/LhhTTVn3xmhMUlQU8y+n02Ag5mdThlYu0PUd598dx+y/lrVQZpnHQAMjDGnB/DuLMZevVWThO2mmoqbOO4DgllNBKIFQH8IwExINkuG69NGVre4MxZ5+hifFZAYTJJxIUcxe8+FcchkxEOo0gWoinII5BoaTZoG4Oj6QHvLFDiA+N1xGNvyk1R90aTb00vFK48gpfivsnQYiRx7z4plBA9QCOmtIlqD7kzvRbTBVg0y7XkVjIr8Wm54tXkl1K990aQNOWxsbDCg2zrdDD/15+dinEBthFM2VzKN7r83zlrqLlQRLBdSPZ2WREqoBUNzGXavoBO4Sb8yNQNCxoLSW7zp9QFv7mnV1cWOho8mCth5J6IGVW5rBYJt2ydrnEcG/hy/dWp2ZS/xPFR9+g7aIDS/vY8K/DQ6VSAV4F75tkJ0NL2kkQASWzIcZedBNmm9V/KnKRR+5X5fOSEkews5jChu+Zzf7ylJ+ukkvkc7J2tC3jak3k1S78rAADTqJ/UiBqYEe7gQxsXMQ2qUoCUlQyP055ItLBZQgjfl/6Sc44rUu1aXgmuUQ1MQxajq7ehYq9D4eRExEHNec4nebQO71pGzHSYGutu73RiRGA==
    TOKEN: AgAak5xn2hMiLdis9xVqUHKVHIEjvm6LQf8C6qbEqzXdP8YhURLfj+tgaUp7tcHn/otuhjAfwWLIKmUyqhLUBsoqWChukRNkpwg24Nz33ERLaxL7ls2kpIwzTA7Ss4FLdOGz7i5bHutGiTp28XtDe8RjDmwBtRyvV6CMQDiuCPFrA1nujHj94rfCop8Yd5xx1WeyTkDwfdx8MWJtZY1DGj7I7bKSwvDBqYYfjMvkXeUqsWEeY0speWC9y7mk2D+H8MD1O0T6Q/ZluyX4pXY9uggCBmumAHtRADfWSMmUgxl+C+2qJnS/rO83L5yRWW7V5/rWts8n+ul+gwd/0uyaaoDlwLmVzZOfRjGKpGCerepP5/nkwtayieSoOSD8L2oFd7JcYQfENIGr8aPRhR8Mqp2Va3s8eAW6XCEOjdq0vEn0Xn9uTjq2dUcz5/Jok8IdDuv9hCWtZfW0cCdUO96r4BYAmXFMtwF/xEz49QrMhaBda0HWHnzMI4Hswz+DEd8VN4a99+uPh5ACsKYIjINtKIjWtFUhRLs1Ub6SUfkzV8/YgR4JI8qhQIif7w9I1A5OWqSaJNB9JziuC2J9yhDBVPrzAKRwlQvMe9RCT6cT6oLOvtbBDqMdmVUXhmqOZK28SwghLzhbzW8oTYnmAmlGZl07lVNoNB4sihf/Cf7QLAUo0c7KVvsoyE+w5tWETa52BtGWyZ0a7+FFa9Pw7itOMvgaz8zqz5vexWT/bGbyFPyAw8747OiEko9u
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: cloudflare-gateway
