apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cloudflare-gateway
      spec:
        replicas: 2
        template:
          spec:
            containers:
            - name: gateway
              image: ghcr.io/pl4nty/cloudflare-kubernetes-gateway:latest  # Use specific version
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
                limits:
                  cpu: 400m
                  memory: 512Mi
              securityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 65534
                allowPrivilegeEscalation: false
    target:
      kind: Deployment
      name: cloudflare-gateway