apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-operator-crds/application.yaml
  - prometheus/application.yaml
  # - prometheus-node-exporter/application.yaml
  # - grafana/dashboards/argo-cd.yaml
 # - httproute.yaml
