apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
 # - httproute.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 66.2.1
    releaseName: prometheus
    namespace: monitoring
    valuesFile: prometheus-values.yaml