grafana:
  enabled: true
  ingress:
    enabled: true
  service:
    type: ClusterIP

prometheus:
  enabled: true
  ingress:
    enabled: false
  service:
    type: ClusterIP

alertmanager:
  enabled: true
  ingress:
    enabled: false
  service:
    type: ClusterIP