apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/harunkilic/argo-fleet
    path: infrastructure/cloudflare-gateway/base
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle