apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/harunkilic/argo-fleet
    path: infrastructure/cloudflare-gateway/overlays/production
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true