apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Ensure this runs after CRDs
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/gitops-repo.git
    targetRevision: HEAD
    path: monitoring/kube-prometheus-stack/base
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring