apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/harunkilic/argo-fleet
    path: infrastructure/sealed-secrets
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: shared-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true