apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    external-dns.alpha.kubernetes.io/target: c9d6f9e3-ce5a-450d-ace3-f24e9a2a1731.cfargotunnel.com
spec:
  rules:
    - host: test.novusweb.pro
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80