---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel-ingress
spec:
  encryptedData:
    credentials.json: AgC2VzLdovdcrKuTDqYpUxtDdWoDlehj33F9CdE38jLhbpUX3IuO7/QRzDCAqAEsRVlCqPLFpVGaD6Kmp26dqibV15ROz0i98tn5vcIRg9ow4EVjNPnUA8cYsYzRUJ5FwdWoVtlKgByCK5oL5ADReAofOBstWt13Rgz4i2wjol72wTYwl1AfHnuqAJ7CgC1GY2PME1m8qtwaS1FKu3upcBmmgNX/SihDoVKAe7mAN4/Ds5QImxtMSm7mf8XJzCXhvK8pz/I3BxwDyKpBkLfoPKw1dfnHiP18Hz2kFmusR1MlOx1/FQnmW5koQJzR9epUJaaQb/zJJrEB4Up5A3NC3E+6jUIZh9MN+RWTdEq+sQKwIS3DUDLMnu4lXMmTGcNU20LHcOAVIjA/ODvNNvxLvxNc5Hjp/6SXNr/2cYuyyoJqAyHUw+OIZZa9vcH3Vbm5S5FJfQ1OUEDtxQx1qEnVP+j1tXVTH7QJAGtQvQFeLpqBHzuFfUvY+Zxbi5Ng6WN3MWCU4frppWM8BzOP6FsnBbQsyG6KAShNFKraGqMU1Qj9p+12nsWfQVslVrXUsblrFulXAQUEm+Pxt6RURA7ISlF9QGthrXciOYtiRuMVdYNh0bZ9a9YyD0CRdYkM7DcUvkbZm0UI0nskBCye6uxGl4R27Pu7qlfUBpIU5Ge0nxPKFT9CxEOJREmsuMhgm1ZniM75yFXEurrHoTdAuFLx3tIIDTUHat3itoJ3pVB9hRfV7jwerZe1yhGMAz0vn1YqlTkHDoy+Nnjb19h74O+Y1dmeJMe1RId3mI6tjr4p1//twJGQL+P3yzBahtq0uuYV1TqHCOUsVGHnhuWdTKI9SfFGQCpmtLR281tw8GKgZ98wOPyq/yyf2xlvMPIWuEwAnqxOiqqMXz8f4me+OlG0E7tOk6k=
    tunnel-id: AgBCEX23APVzHEplwWTurSdrE/QX7d8jb6e3KFTUgt1SIkApcOKuB8NxfXnE+02NdIp/nfYK/MwLxalGfwmRD9TXur770TSRsf4EIHtCPc7uCUKZZLe9UbhX2gHLlVnRVJhyd38rYl6COvZ7LGgVhDnDMWZjyxb9VTbAofdmpinAV/ypD67vZdycXNaV8aAn8rdB8WavR5L/93NGyYXcPD3FrM1tySAn+tAQ9Hs6y2YrOB1rVR+Qs+sCTy9hClXOW5orClYU1ybWzsXt5SlfB2FCNmM7dQb6MHSG7fuyVQWUiEeYO+KObBXqeB+vN/QO/fK6GOV5lBnKS8SOkT0SkhiEsGKlx5XTPPvmbJxFAhkiZlFEs6pWNCqfdJ2tG89kZzP50Ej8z3jabskxVXo8u9sxcHwxREfvNYS/57YS5Ztnbw5NPfnojYk/VJ0f1Hmrvhema1A4f3A8gs0biS9P5uKXik/D9HqkGOg4UM5s8GM98PC6aDxwMQsbaUZVLy7lfyqkOLbZu0xBDyCPg1vvj0vWVXIoGKTVV4R7UvHbwhDwLxHaEuIUHfGu8X1HoVYvK8gNH50eJ4vnGz0KUJH/E5CR+pAYV2FpcTH6oGEtMH51DYnlUx0izG9JjmE7hC+k/53gPTNHFNm5Sjz8atdIg+q30zbQa/imsTm06DWZqjJp7TlwKnN06EUGXb+S+PbENjOcssTbvfXIIF78ig9IjbtWgh+WRcWObm0Ng7ICHDFxRp6gGAs=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-credentials
      namespace: cloudflare-tunnel-ingress
    type: Opaque
