apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/configmap-patch.yaml

namespace: cloudflare