apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    tunnel: c9d6f9e3-ce5a-450d-ace3-f24e9a2a1731
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: "*.novusweb.pro"
        service: https://ingress-nginx-controller.ingress-nginx.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
          connectionTimeout: 10s
          keepAliveTimeout: 30s
          keepAliveConnections: 100
          disableChunkedEncoding: true
      - service: http_status:404
    metrics: 0.0.0.0:2000
    no-autoupdate: true