apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    tunnel: c9d6f9e3-ce5a-450d-ace3-f24e9a2a1731
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: "*.novusweb.pro"
        service: https://kubernetes.default.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
      - service: http_status:404