---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgALEgr9XgZKw72KQRSclMUhOs8jhVjcCIfJwEfmtpOk9LZjmjMsUYMIew0b3SPowim422EmtYgQWnIpUk7d2kLBbn0f3QIN3xk5FFsB6SDxV6r+xyTlS8dqmmEMEMyI8ELj1N0zFMjWhs7l0QwCjcfUU54EHR8qLJiaRPYMavTZ8/+Z5z0zHjwQVLSSrKArLkRU7ywvE+7JTMC8s3PE2BRUVjk88vmT30kkbg+yDKuSHrZety/WPQ6qEyWMIgLzHsSJczV6gR/QWsUgIu/gqrXw1JOGQbkC4CR97PZbJZ0526FbtBow3CB7ggGPHoX1jnlStmtKUP0jzeS5m4JTli1IJne+EKBo2CQuJTwoYWxbkNryb5RfSg9DYM5X0XtYZWYBimGWwO1U5u3s0suZ5amC2TqC5FbNHPVkPUpZZmFmObg2Ca90h3KJGMLQSoz6l2RbziOSjO1b10ffGVCBM44YSCgy3U0SRW/toa7bX5girw1EYoRuhFgb/bDL21cRa3Hm2b/Z2V32sXXTDXghSF0yr5Kypwq0ovLzAu0tbCoGdVjvPhYKKNq/IbO7+vQsFlAE7wxqyDc+lrgxr/fJZt0/Kg/lHfnJykAPTnGoh0I2e7WD4Mg01hmDwhwi6Tm+hGU0lZjqTkh3bZlZ/ucVBTnMaXKRomhcbyckITVHjUrmHg/0UQmZPRAoUp6PEVUa2LBWE2LMaqxLo7+uWWbrNQhKhb/BlRKWlcPNqVt3WXpKOKbfDNoeE2A+wELxe39X1nMoNm7hJNtcud2W/ruAHKopWbt2/T3oql+wdD93GaABkoXdBK5xuiCwk+AwJDvXv8+jqcaC3I1vocNnJn3MBiGwCpbCIVCEEbaGQ0W7Ge2wXhTlORdqioBOlcubBuBw0M8mRBUoXbY9rbnKVAK8xnorOI4=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: cloudflare
    type: Opaque
